### ISSUE TITLE
class method describe in fabric.py region variable unused

### ISSUE THREAD

**Issue by SDBrett** [grantorchard/caspyr#19]
The class method describe has an input variable called 'region' when is displaying as unused. On line 45 it appears that region is meant to be used to form part of the URL. 

`    @classmethod
    def describe(cls, session, image, region):
        """
        Used to create an instance of the image class. Image details are
        unique by 'region', so the region must be provided.
        :param session: An instance of the Session class.
        :type session: Session
        :param image: The name of the image you want to describe.
        :type image: string
        :param region: The external region id value (friendly name of the
        region - eg. westus or us-west-1).
        :return: Returns an instance of the image claass.
        :rtype: Image
        """

        uri = (f'/iaas/fabric-images?$filter=(name eq \'{image}\') and '
               '(externalRegionId eq {region})')
        j = session._request(f'{session.baseurl}{uri}')['content'][0]
        return cls(j)`

**Comment by grantorchard** [comment]
PR merged to resolve this.
