### ISSUE TITLE
Session class _request method PEP8

### ISSUE THREAD

**Issue by SDBrett** [grantorchard/caspyr#23]
The method _request in the Session class starts with an underscore which is generating PEP8 violations. 

Is there a reason for the method to start with an underscore or can it be refactored?

**Comment by russellpope** [comment]
Mostly to denote it as a “private” method for the consumer of the API. It’s a convention used elsewhere though not specifically PEP8.

Sent from my iPhone

On Nov 28, 2018, at 2:23 PM, SDBrett <notifications@github.com<mailto:notifications@github.com>> wrote:


The method _request in the Session class starts with an underscore which is generating PEP8 violations.

Is there a reason for the method to start with an underscore or can it be refactored?

**Comment by SDBrett** [comment]
Thanks for the info @russellpope
